/*
 * Codegen writer for the C backend of Newton.
 * Newton (C) 2023
 */

#[derive(Debug, Clone)]
pub struct CodegenWriter {
    output: String,
}

impl CodegenWriter {
    pub fn new() -> Self {
        Self {
            output: String::from("// This code has been automatically generated by Newton's C backend.\n")
        }
    }

    pub fn emit(&mut self, code: &String) -> () {
        self.output.push_str(code);
    }

    pub fn generate_header(&mut self) -> () {

    }

    #[inline]
    pub fn output(&mut self) -> &String {
        &self.output
    }
}
