/*
 * Codegen writer for the C backend of Newton.
 * Newton (C) 2023
 */

#[derive(Debug, Clone)]
pub struct CodegenWriter {
    pub output: String,
}

impl CodegenWriter {
    pub fn new(&mut self) -> Self {
        Self {
            output: String::from("// This code has been automatically generated by Newton's C backend.")
        }
    }

    pub fn emit(&mut self, code: &String) -> () {
        self.output.push_str(code);
    }

    pub fn generate_struct(&mut self) -> () {
        self.emit(&format!("typedef struct {{"));

        self.emit(&format!("}} ;"));
    }

    pub fn generate_enum(&mut self) -> () {}

    pub fn generate_function(&mut self) -> () {}

    pub fn generate_header(&mut self) -> () {

    }
}
